# Generated by Django 4.2 on 2023-04-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_hospital_mediator_nurse_shiftapplication_workshift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='mediator',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='mediator',
        ),
    ]
