# Generated by Django 4.2 on 2023-04-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_hospital_mediator_remove_nurse_mediator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shiftapplication',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='shiftapplication',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Mediator',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='ShiftApplication',
        ),
        migrations.DeleteModel(
            name='WorkShift',
        ),
    ]
