# Generated by Django 4.2 on 2023-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
