# Generated by Django 4.2 on 2023-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_workshift_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftapplication',
            name='application_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='PENDING', max_length=200),
        ),
    ]
