# Generated by Django 4.2 on 2023-04-21 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
