# Generated by Django 4.2 on 2023-04-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_hospital', '0002_job_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
